### ISSUE TITLE
Typo in readme example

### ISSUE THREAD

**Issue by tedmiston** [kennethreitz/clint#115]
The example with colored console text ("I want to color my console text. ...") forgets to import puts.

`from clint.textui import colored`
should be
`from clint.textui import colored, puts`

OTOH, if making the assumption that the user is typing all examples in sequentially and it's acceptable for them to be incomplete, I think this should be made more explicit to prevent confusion.

**Comment by wkentaro** [comment]
This is fixed and should be closed.
