### ISSUE TITLE
Colored output combined with `input` and `raw_input`

### ISSUE THREAD

**Issue by DanielAndreasen** [kennethreitz/clint#119]
Hi Kenneth,

I love this module for coloring the output to my terminal, it's fantastic. However, I have a script which requires user input via either `input` or `raw_input` something like this

    na = raw_input("What is your name > ")

Here I would like to color `name` yellow. Is there a (simple) way to do that? My current workaround is

    puts("What is your "+colored.yellow("name"))
    na = raw_input("> ")

but this is obviosly written in two lines instead of one which I prefer.

Cheers,
Daniel

**Comment by hhk1989** [comment]
You can just do

`na = raw_input("What is your " + clint.textui.colored.yellow("name"))`

**Comment by eiszfuchs** [comment]
I like formatting strings with `%`.
Also, you might as well use everything from `clint`.

```python
from clint.textui import prompt, colored

information = {}
message = "What is your %s? > "

for prop in ["name", "birthday"]:
    information[prop] = prompt.query(message % colored.yellow(prop))

print(information)
```

```
What is your name? > eiszfuchs
What is your birthday? > 13/10/1988
{'birthday': '13/10/1988', 'name': 'eiszfuchs'}
```

**Comment by DanielAndreasen** [comment]
Thanks for the help both of you.
@eiszfuchs you are exactly 11 months older than me, if that is your birthday :smile:
