### ISSUE TITLE
Colored text doesn't work with logging

### ISSUE THREAD

**Issue by APerson241** [kennethreitz/clint#137]
This works:

    >>> from clint.textui import colored
    >>> print(colored.green("Test"))
    Test

Here, the "`Test`" is green, as expected.

But this doesn't work:

    >>> import logging
    >>> logging.getLogger().addHandler(logging.StreamHandler())
    >>> from clint.textui import colored
    >>> logging.critical(colored.green("Test"))
    ←[32m←[22mTest←[39m←[22m

In that case, the "`Test`" is not green and the escape sequences are visible.

**Comment by wkentaro** [comment]
In my env, it works.
So maybe this problem is fixed in the latest version, or your env is unexpected one.
```
% cat log.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from clint.textui import colored
print(colored.green("Test"))

import logging
logging.getLogger().addHandler(logging.StreamHandler())
from clint.textui import colored
logging.critical(colored.green("Test"))

% python log.py
Test
Test
```

**Comment by APerson241** [comment]
I can't actually reproduce this anymore, so it's likely that something in the latest version fixed it.
