### ISSUE TITLE
Pypi package is outdated

### ISSUE THREAD

**Issue by neara** [kennethreitz/clint#143]
I pip installed clint, and the version i got didn't have `prompt.options` and `validators.OptionValidator`.

**Comment by mflaxman** [comment]
+1

**Comment by wkentaro** [comment]
+1

**Comment by magicshui** [comment]
+1

**Comment by jpiper** [comment]
Hi all - I'm in Cambodia at the moment and don't have access to a computer. I'll push a new version to pypi within the next week!

J

**Comment by jpiper** [comment]
Done!
