### ISSUE TITLE
clint 0.4.1 on pypi is not actul with master repo

### ISSUE THREAD

**Issue by vmalyi** [kennethreitz/clint#149]
I've noticed that currently actual clint package on pypi has version 0.4.1 but it doesn't correspond to the latest master state here on github which is on 140d85898de385ed1c799ecdd0e1f5fe9ea2025e.

Could you please upload the latest version to pypi so that fresh functionality like "options" is available? 

Thanks!

**Comment by jpiper** [comment]
Done!

**Comment by vmalyi** [comment]
Thanks Jason!
